[package]
name = "axtask"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS task management module"
license.workspace = true
homepage.workspace = true
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axtask"
documentation = "https://arceos-org.github.io/arceos/axtask/index.html"

[features]
default = []

multitask = [
    "dep:axconfig",
    "dep:axalloc",
    "dep:percpu",
    "dep:kspin",
    "dep:memory_addr",
    "dep:axsched",
    "dep:timer_list",
    "kernel_guard",
    "dep:crate_interface",
    "dep:cpumask",
]
irq = []
ipi = ["irq", "dep:axipi"]
tls = ["axhal/tls"]
preempt = ["irq", "percpu?/preempt", "kernel_guard/preempt"]
smp = ["kspin/smp"]
qperf-trace = ["multitask"]

sched-fifo = ["multitask"]
sched-rr = ["multitask", "preempt"]
sched-cfs = ["multitask", "preempt"]
sched-load-balance = ["multitask"]

test = ["percpu?/sp-naive"]

[dependencies]
cfg-if.workspace = true
log.workspace = true
axhal.workspace = true
axerrno.workspace = true
axconfig = { workspace = true, optional = true }
axalloc = { workspace = true, optional = true }
percpu = { workspace = true, optional = true }
kspin = { workspace = true, optional = true }
lazyinit.workspace = true
memory_addr = { workspace = true, optional = true }
timer_list = { workspace = true, optional = true }
kernel_guard = { workspace = true, optional = true }
crate_interface = { workspace = true, optional = true }
cpumask = { workspace = true, optional = true }
axsched = { workspace = true, optional = true }
axpoll.workspace = true
axio.workspace = true
futures-util.workspace = true
axipi = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true
axhal = { workspace = true, features = ["fp-simd"] }
axtask = { workspace = true, features = ["test", "multitask"] }
