[package]
name = "axfs"
version.workspace = true
edition.workspace = true
authors = ["Mivik <mivikq@gmail.com>"]
description = "ArceOS filesystem module"
license.workspace = true
homepage.workspace = true

[features]
default = ["ext4"]
use-ramdisk = []       # TODO: init ramdisk
fat = ["dep:fatfs"]
ext4 = ["dep:ext4plus"]
times = []
std = []
pre-testcode = []
final-testcode = []
buildstorm-stats = []

[dependencies]
axalloc.workspace = true
axconfig.workspace = true
axtask.workspace = true
axdriver = { workspace = true, features = ["block", "async"] }
axerrno.workspace = true
axfs-ng-vfs.workspace = true
axhal.workspace = true
axio = { workspace = true, features = ["alloc"] }
axpoll.workspace = true
axsync.workspace = true
bitflags.workspace = true
cfg-if.workspace = true
chrono.workspace = true
intrusive-collections.workspace = true
kspin.workspace = true
log.workspace = true
lru.workspace = true
rand_core.workspace = true
rand_pcg.workspace = true
scope-local.workspace = true
slab.workspace = true
spin.workspace = true
async-trait.workspace = true
async-lock.workspace = true
ext4plus = { workspace = true, features = ["multi-threaded"], optional = true }
futures-util.workspace = true
heapless.workspace = true

[dependencies.fatfs]
workspace = true
features = ["alloc", "lfn", "log_level_trace", "unicode"]
optional = true

[dev-dependencies]
axdriver = { workspace = true, features = ["block", "ramdisk", "async"] }
env_logger.workspace = true
