//! PulseOS platform support for the StarFive VisionFive 2 (JH7110).
//!
//! U-Boot/OpenSBI enters the kernel with the boot hart in `a0` and the live
//! board device tree in `a1`. The platform requires that handoff and derives
//! RAM, available U74 harts, and PLIC contexts from that DTB.

#![no_std]

#[macro_use]
extern crate log;
#[macro_use]
extern crate axplat;

mod boot;
mod console;
mod cpu_topology;
mod init;
#[cfg(feature = "irq")]
mod irq;
mod mem;
mod plic;
mod power;
mod rtc_decode;
mod time;
mod tlb;
mod topology;

pub mod config {
    //! Platform configuration module.
    //!
    //! `AX_CONFIG_PATH` is generated by the PulseOS build. The crate-local
    //! configuration is used only when compiling this package independently.
    axconfig_macros::include_configs!(path_env = "AX_CONFIG_PATH", fallback = "axconfig.toml");
    assert_str_eq!(
        PACKAGE,
        env!("CARGO_PKG_NAME"),
        "`PACKAGE` field in the configuration does not match the package name."
    );
}
